# Reference: https://www.exclamationlabs.com/blog/continuous-deployment-to-npm-using-gitlab-ci/

# GitLab uses docker in the background, so we need to specify the 
# image versions. This is useful because we're freely to use
# multiple node versions to work with it. They come from the docker
# repo.
# Uses NodeJS V 12.5.0
# image: node:alpine

# And to cache them as well.
cache:
  paths:
    - node_modules/
    - .yarn

# We tell GitLab to install all the packages
# before running anything.
# Docker images come with yarn preinstalled
before_script:  
  - apt-get update -qq && apt-get install

# You specify the stages. Those are the steps that GitLab will go through 
# Order matters. 
stages:
  - build
  - staging
  - production

Build:
  image: node:12.5.0
  stage: build
  before_script: 
    - yarn config set cache-folder .yarn
    - yarn install 
  script:
    - yarn build
  artifacts:
    expire_in: 1 week
    paths:
      - build

Deploy to Staging:
  image: alpine
  stage: staging
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav --delete build/ ubuntu@54.250.146.205:repo/sol-web/develop/build
  only:
    - develop

Deploy to Production:
  image: alpine
  stage: production
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav --delete build/ ubuntu@54.250.146.205:repo/sol-web/master/build
  only:
    - master